package chat.donzi.localtavern.ui.components

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.size
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Canvas
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.Paint
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import chat.donzi.localtavern.data.sync.QrCode

// Renders the pairing QR code on any platform. The QR itself is generated by
// the pure-Kotlin encoder (data/sync/QrCodeGenerator.kt) and drawn once into
// an ImageBitmap; only the bitmap is shown on recompositions.
@Composable
fun QrCodeImage(
    text: String,
    modifier: Modifier = Modifier,
    size: Dp = 220.dp,
    quietZoneModules: Int = 4
) {
    val bitmap = remember(text) {
        runCatching {
            val qr = QrCode.encodeText(text, QrCode.Ecc.MEDIUM)
            val scale = 8
            val totalModules = qr.size + quietZoneModules * 2
            val pixelSize = totalModules * scale
            val image: ImageBitmap = ImageBitmap(pixelSize, pixelSize)
            val canvas = Canvas(image)
            val white = Paint().apply { color = Color.White }
            canvas.drawRect(0f, 0f, pixelSize.toFloat(), pixelSize.toFloat(), white)
            val black = Paint().apply { color = Color.Black }
            for (y in 0 until qr.size) {
                for (x in 0 until qr.size) {
                    if (qr.getModule(x, y)) {
                        val left = (x + quietZoneModules) * scale
                        val top = (y + quietZoneModules) * scale
                        canvas.drawRect(
                            left = left.toFloat(),
                            top = top.toFloat(),
                            right = (left + scale).toFloat(),
                            bottom = (top + scale).toFloat(),
                            paint = black
                        )
                    }
                }
            }
            image
        }.getOrNull()
    }
    if (bitmap != null) {
        Image(
            bitmap = bitmap,
            contentDescription = null,
            modifier = modifier.size(size)
        )
    }
}
